// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/url"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for GetProductsParamsExpiry.
const (
	All     GetProductsParamsExpiry = "all"
	Expired GetProductsParamsExpiry = "expired"
	Soon    GetProductsParamsExpiry = "soon"
)

// Defines values for GetProductsParamsRole.
const (
	Grocery    GetProductsParamsRole = "grocery"
	Restaurant GetProductsParamsRole = "restaurant"
)

// PostAdminApprovalsIdApproveJSONBody defines parameters for PostAdminApprovalsIdApprove.
type PostAdminApprovalsIdApproveJSONBody struct {
	Notes *string `json:"notes,omitempty"`
}

// PostAdminApprovalsIdRejectJSONBody defines parameters for PostAdminApprovalsIdReject.
type PostAdminApprovalsIdRejectJSONBody struct {
	Notes *string `json:"notes,omitempty"`
}

// PostAdminComplaintsIdResolveJSONBody defines parameters for PostAdminComplaintsIdResolve.
type PostAdminComplaintsIdResolveJSONBody struct {
	RefundAmount    *float32 `json:"refund_amount,omitempty"`
	ResolutionNotes *string  `json:"resolution_notes,omitempty"`
}

// PostAdminOnboardingLeadsIdNotifyJSONBody defines parameters for PostAdminOnboardingLeadsIdNotify.
type PostAdminOnboardingLeadsIdNotifyJSONBody struct {
	Channel *string `json:"channel,omitempty"`
	Message *string `json:"message,omitempty"`
}

// PostAdminPartnersIdSuspendJSONBody defines parameters for PostAdminPartnersIdSuspend.
type PostAdminPartnersIdSuspendJSONBody struct {
	Reason *string `json:"reason,omitempty"`
}

// PostAuthLoginJSONBody defines parameters for PostAuthLogin.
type PostAuthLoginJSONBody struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

// PatchAuthProfileJSONBody defines parameters for PatchAuthProfile.
type PatchAuthProfileJSONBody = map[string]interface{}

// PostAuthSendOtpJSONBody defines parameters for PostAuthSendOtp.
type PostAuthSendOtpJSONBody struct {
	Email    *string `json:"email,omitempty"`
	Mobile   *string `json:"mobile,omitempty"`
	Type     *string `json:"type,omitempty"`
	UserType *string `json:"user_type,omitempty"`
}

// PostAuthSignupJSONBody defines parameters for PostAuthSignup.
type PostAuthSignupJSONBody struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	UserType *string `json:"user_type,omitempty"`
}

// PostAuthVerifyOtpJSONBody defines parameters for PostAuthVerifyOtp.
type PostAuthVerifyOtpJSONBody struct {
	Otp    *string `json:"otp,omitempty"`
	UserId *string `json:"user_id,omitempty"`
}

// PostDeliveryOnboardingJSONBody defines parameters for PostDeliveryOnboarding.
type PostDeliveryOnboardingJSONBody = map[string]interface{}

// PostDeliveryRecommendationsAckJSONBody defines parameters for PostDeliveryRecommendationsAck.
type PostDeliveryRecommendationsAckJSONBody struct {
	Id *string `json:"id,omitempty"`
}

// PostGroceryOnboardingJSONBody defines parameters for PostGroceryOnboarding.
type PostGroceryOnboardingJSONBody = map[string]interface{}

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	Status   *string `form:"status,omitempty" json:"status,omitempty"`
	OutletId *string `form:"outlet_id,omitempty" json:"outlet_id,omitempty"`
}

// PostOrdersOrderIdAssignDeliveryJSONBody defines parameters for PostOrdersOrderIdAssignDelivery.
type PostOrdersOrderIdAssignDeliveryJSONBody struct {
	DeliveryPersonId *string `json:"delivery_person_id,omitempty"`
}

// PatchOrdersOrderIdStatusJSONBody defines parameters for PatchOrdersOrderIdStatus.
type PatchOrdersOrderIdStatusJSONBody = map[string]interface{}

// GetProductsParams defines parameters for GetProducts.
type GetProductsParams struct {
	Category *string                  `form:"category,omitempty" json:"category,omitempty"`
	Stock    *string                  `form:"stock,omitempty" json:"stock,omitempty"`
	Promo    *bool                    `form:"promo,omitempty" json:"promo,omitempty"`
	Expiry   *GetProductsParamsExpiry `form:"expiry,omitempty" json:"expiry,omitempty"`
	Role     *GetProductsParamsRole   `form:"role,omitempty" json:"role,omitempty"`
}

// GetProductsParamsExpiry defines parameters for GetProducts.
type GetProductsParamsExpiry string

// GetProductsParamsRole defines parameters for GetProducts.
type GetProductsParamsRole string

// PatchProductsIdJSONBody defines parameters for PatchProductsId.
type PatchProductsIdJSONBody = map[string]interface{}

// PostAdminApprovalsIdApproveJSONRequestBody defines body for PostAdminApprovalsIdApprove for application/json ContentType.
type PostAdminApprovalsIdApproveJSONRequestBody PostAdminApprovalsIdApproveJSONBody

// PostAdminApprovalsIdRejectJSONRequestBody defines body for PostAdminApprovalsIdReject for application/json ContentType.
type PostAdminApprovalsIdRejectJSONRequestBody PostAdminApprovalsIdRejectJSONBody

// PostAdminComplaintsIdResolveJSONRequestBody defines body for PostAdminComplaintsIdResolve for application/json ContentType.
type PostAdminComplaintsIdResolveJSONRequestBody PostAdminComplaintsIdResolveJSONBody

// PostAdminOnboardingLeadsIdNotifyJSONRequestBody defines body for PostAdminOnboardingLeadsIdNotify for application/json ContentType.
type PostAdminOnboardingLeadsIdNotifyJSONRequestBody PostAdminOnboardingLeadsIdNotifyJSONBody

// PostAdminPartnersIdSuspendJSONRequestBody defines body for PostAdminPartnersIdSuspend for application/json ContentType.
type PostAdminPartnersIdSuspendJSONRequestBody PostAdminPartnersIdSuspendJSONBody

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody PostAuthLoginJSONBody

// PatchAuthProfileJSONRequestBody defines body for PatchAuthProfile for application/json ContentType.
type PatchAuthProfileJSONRequestBody = PatchAuthProfileJSONBody

// PostAuthSendOtpJSONRequestBody defines body for PostAuthSendOtp for application/json ContentType.
type PostAuthSendOtpJSONRequestBody PostAuthSendOtpJSONBody

// PostAuthSignupJSONRequestBody defines body for PostAuthSignup for application/json ContentType.
type PostAuthSignupJSONRequestBody PostAuthSignupJSONBody

// PostAuthVerifyOtpJSONRequestBody defines body for PostAuthVerifyOtp for application/json ContentType.
type PostAuthVerifyOtpJSONRequestBody PostAuthVerifyOtpJSONBody

// PostDeliveryOnboardingJSONRequestBody defines body for PostDeliveryOnboarding for application/json ContentType.
type PostDeliveryOnboardingJSONRequestBody = PostDeliveryOnboardingJSONBody

// PostDeliveryRecommendationsAckJSONRequestBody defines body for PostDeliveryRecommendationsAck for application/json ContentType.
type PostDeliveryRecommendationsAckJSONRequestBody PostDeliveryRecommendationsAckJSONBody

// PostGroceryOnboardingJSONRequestBody defines body for PostGroceryOnboarding for application/json ContentType.
type PostGroceryOnboardingJSONRequestBody = PostGroceryOnboardingJSONBody

// PostOrdersOrderIdAssignDeliveryJSONRequestBody defines body for PostOrdersOrderIdAssignDelivery for application/json ContentType.
type PostOrdersOrderIdAssignDeliveryJSONRequestBody PostOrdersOrderIdAssignDeliveryJSONBody

// PatchOrdersOrderIdStatusJSONRequestBody defines body for PatchOrdersOrderIdStatus for application/json ContentType.
type PatchOrdersOrderIdStatusJSONRequestBody = PatchOrdersOrderIdStatusJSONBody

// PatchProductsIdJSONRequestBody defines body for PatchProductsId for application/json ContentType.
type PatchProductsIdJSONRequestBody = PatchProductsIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin/approvals)
	GetAdminApprovals(c *fiber.Ctx) error

	// (POST /admin/approvals/{id}/approve)
	PostAdminApprovalsIdApprove(c *fiber.Ctx, id string) error

	// (POST /admin/approvals/{id}/reject)
	PostAdminApprovalsIdReject(c *fiber.Ctx, id string) error

	// (GET /admin/complaints)
	GetAdminComplaints(c *fiber.Ctx) error

	// (GET /admin/complaints/{id}/investigation)
	GetAdminComplaintsIdInvestigation(c *fiber.Ctx, id string) error

	// (POST /admin/complaints/{id}/resolve)
	PostAdminComplaintsIdResolve(c *fiber.Ctx, id string) error

	// (GET /admin/onboarding-leads)
	GetAdminOnboardingLeads(c *fiber.Ctx) error

	// (POST /admin/onboarding-leads/{id}/notify)
	PostAdminOnboardingLeadsIdNotify(c *fiber.Ctx, id string) error

	// (GET /admin/partners)
	GetAdminPartners(c *fiber.Ctx) error

	// (POST /admin/partners/{id}/suspend)
	PostAdminPartnersIdSuspend(c *fiber.Ctx, id string) error

	// (GET /admin/reports/kpis)
	GetAdminReportsKpis(c *fiber.Ctx) error

	// (POST /auth/login)
	PostAuthLogin(c *fiber.Ctx) error

	// (GET /auth/me)
	GetAuthMe(c *fiber.Ctx) error

	// (PATCH /auth/profile)
	PatchAuthProfile(c *fiber.Ctx) error

	// (POST /auth/send-otp)
	PostAuthSendOtp(c *fiber.Ctx) error

	// (POST /auth/signup)
	PostAuthSignup(c *fiber.Ctx) error

	// (POST /auth/verify-otp)
	PostAuthVerifyOtp(c *fiber.Ctx) error

	// (GET /delivery/active-task)
	GetDeliveryActiveTask(c *fiber.Ctx) error

	// (GET /delivery/earnings-insights)
	GetDeliveryEarningsInsights(c *fiber.Ctx) error

	// (GET /delivery/earnings/weekly)
	GetDeliveryEarningsWeekly(c *fiber.Ctx) error

	// (GET /delivery/kpis)
	GetDeliveryKpis(c *fiber.Ctx) error

	// (POST /delivery/onboarding)
	PostDeliveryOnboarding(c *fiber.Ctx) error

	// (GET /delivery/profile)
	GetDeliveryProfile(c *fiber.Ctx) error

	// (GET /delivery/recommendations)
	GetDeliveryRecommendations(c *fiber.Ctx) error

	// (POST /delivery/recommendations/ack)
	PostDeliveryRecommendationsAck(c *fiber.Ctx) error

	// (GET /delivery/shifts)
	GetDeliveryShifts(c *fiber.Ctx) error

	// (GET /delivery/sla-kpis)
	GetDeliverySlaKpis(c *fiber.Ctx) error

	// (GET /delivery/trace/{orderId})
	GetDeliveryTraceOrderId(c *fiber.Ctx, orderId string) error

	// (GET /grocery/expiry-alerts)
	GetGroceryExpiryAlerts(c *fiber.Ctx) error

	// (GET /grocery/kpis)
	GetGroceryKpis(c *fiber.Ctx) error

	// (POST /grocery/onboarding)
	PostGroceryOnboarding(c *fiber.Ctx) error

	// (GET /grocery/payout-summary)
	GetGroceryPayoutSummary(c *fiber.Ctx) error

	// (GET /grocery/profile)
	GetGroceryProfile(c *fiber.Ctx) error

	// (GET /grocery/stock-alerts)
	GetGroceryStockAlerts(c *fiber.Ctx) error

	// (GET /orders)
	GetOrders(c *fiber.Ctx, params GetOrdersParams) error

	// (POST /orders/{order_id}/assign-delivery)
	PostOrdersOrderIdAssignDelivery(c *fiber.Ctx, orderId string) error

	// (PATCH /orders/{order_id}/status)
	PatchOrdersOrderIdStatus(c *fiber.Ctx, orderId string) error

	// (GET /products)
	GetProducts(c *fiber.Ctx, params GetProductsParams) error

	// (GET /products/auto-discounts)
	GetProductsAutoDiscounts(c *fiber.Ctx) error

	// (GET /products/expiry-alerts)
	GetProductsExpiryAlerts(c *fiber.Ctx) error

	// (PATCH /products/{id})
	PatchProductsId(c *fiber.Ctx, id string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetAdminApprovals operation middleware
func (siw *ServerInterfaceWrapper) GetAdminApprovals(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetAdminApprovals(c)
}

// PostAdminApprovalsIdApprove operation middleware
func (siw *ServerInterfaceWrapper) PostAdminApprovalsIdApprove(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAdminApprovalsIdApprove(c, id)
}

// PostAdminApprovalsIdReject operation middleware
func (siw *ServerInterfaceWrapper) PostAdminApprovalsIdReject(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAdminApprovalsIdReject(c, id)
}

// GetAdminComplaints operation middleware
func (siw *ServerInterfaceWrapper) GetAdminComplaints(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetAdminComplaints(c)
}

// GetAdminComplaintsIdInvestigation operation middleware
func (siw *ServerInterfaceWrapper) GetAdminComplaintsIdInvestigation(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetAdminComplaintsIdInvestigation(c, id)
}

// PostAdminComplaintsIdResolve operation middleware
func (siw *ServerInterfaceWrapper) PostAdminComplaintsIdResolve(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAdminComplaintsIdResolve(c, id)
}

// GetAdminOnboardingLeads operation middleware
func (siw *ServerInterfaceWrapper) GetAdminOnboardingLeads(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetAdminOnboardingLeads(c)
}

// PostAdminOnboardingLeadsIdNotify operation middleware
func (siw *ServerInterfaceWrapper) PostAdminOnboardingLeadsIdNotify(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAdminOnboardingLeadsIdNotify(c, id)
}

// GetAdminPartners operation middleware
func (siw *ServerInterfaceWrapper) GetAdminPartners(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetAdminPartners(c)
}

// PostAdminPartnersIdSuspend operation middleware
func (siw *ServerInterfaceWrapper) PostAdminPartnersIdSuspend(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAdminPartnersIdSuspend(c, id)
}

// GetAdminReportsKpis operation middleware
func (siw *ServerInterfaceWrapper) GetAdminReportsKpis(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetAdminReportsKpis(c)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAuthLogin(c)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetAuthMe(c)
}

// PatchAuthProfile operation middleware
func (siw *ServerInterfaceWrapper) PatchAuthProfile(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PatchAuthProfile(c)
}

// PostAuthSendOtp operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSendOtp(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAuthSendOtp(c)
}

// PostAuthSignup operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSignup(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAuthSignup(c)
}

// PostAuthVerifyOtp operation middleware
func (siw *ServerInterfaceWrapper) PostAuthVerifyOtp(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAuthVerifyOtp(c)
}

// GetDeliveryActiveTask operation middleware
func (siw *ServerInterfaceWrapper) GetDeliveryActiveTask(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetDeliveryActiveTask(c)
}

// GetDeliveryEarningsInsights operation middleware
func (siw *ServerInterfaceWrapper) GetDeliveryEarningsInsights(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetDeliveryEarningsInsights(c)
}

// GetDeliveryEarningsWeekly operation middleware
func (siw *ServerInterfaceWrapper) GetDeliveryEarningsWeekly(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetDeliveryEarningsWeekly(c)
}

// GetDeliveryKpis operation middleware
func (siw *ServerInterfaceWrapper) GetDeliveryKpis(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetDeliveryKpis(c)
}

// PostDeliveryOnboarding operation middleware
func (siw *ServerInterfaceWrapper) PostDeliveryOnboarding(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostDeliveryOnboarding(c)
}

// GetDeliveryProfile operation middleware
func (siw *ServerInterfaceWrapper) GetDeliveryProfile(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetDeliveryProfile(c)
}

// GetDeliveryRecommendations operation middleware
func (siw *ServerInterfaceWrapper) GetDeliveryRecommendations(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetDeliveryRecommendations(c)
}

// PostDeliveryRecommendationsAck operation middleware
func (siw *ServerInterfaceWrapper) PostDeliveryRecommendationsAck(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostDeliveryRecommendationsAck(c)
}

// GetDeliveryShifts operation middleware
func (siw *ServerInterfaceWrapper) GetDeliveryShifts(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetDeliveryShifts(c)
}

// GetDeliverySlaKpis operation middleware
func (siw *ServerInterfaceWrapper) GetDeliverySlaKpis(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetDeliverySlaKpis(c)
}

// GetDeliveryTraceOrderId operation middleware
func (siw *ServerInterfaceWrapper) GetDeliveryTraceOrderId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", c.Params("orderId"), &orderId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter orderId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetDeliveryTraceOrderId(c, orderId)
}

// GetGroceryExpiryAlerts operation middleware
func (siw *ServerInterfaceWrapper) GetGroceryExpiryAlerts(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetGroceryExpiryAlerts(c)
}

// GetGroceryKpis operation middleware
func (siw *ServerInterfaceWrapper) GetGroceryKpis(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetGroceryKpis(c)
}

// PostGroceryOnboarding operation middleware
func (siw *ServerInterfaceWrapper) PostGroceryOnboarding(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostGroceryOnboarding(c)
}

// GetGroceryPayoutSummary operation middleware
func (siw *ServerInterfaceWrapper) GetGroceryPayoutSummary(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetGroceryPayoutSummary(c)
}

// GetGroceryProfile operation middleware
func (siw *ServerInterfaceWrapper) GetGroceryProfile(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetGroceryProfile(c)
}

// GetGroceryStockAlerts operation middleware
func (siw *ServerInterfaceWrapper) GetGroceryStockAlerts(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetGroceryStockAlerts(c)
}

// GetOrders operation middleware
func (siw *ServerInterfaceWrapper) GetOrders(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrdersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", query, &params.Status)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter status: %w", err).Error())
	}

	// ------------- Optional query parameter "outlet_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "outlet_id", query, &params.OutletId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter outlet_id: %w", err).Error())
	}

	return siw.Handler.GetOrders(c, params)
}

// PostOrdersOrderIdAssignDelivery operation middleware
func (siw *ServerInterfaceWrapper) PostOrdersOrderIdAssignDelivery(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", c.Params("order_id"), &orderId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter order_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostOrdersOrderIdAssignDelivery(c, orderId)
}

// PatchOrdersOrderIdStatus operation middleware
func (siw *ServerInterfaceWrapper) PatchOrdersOrderIdStatus(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", c.Params("order_id"), &orderId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter order_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PatchOrdersOrderIdStatus(c, orderId)
}

// GetProducts operation middleware
func (siw *ServerInterfaceWrapper) GetProducts(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProductsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameter("form", true, false, "category", query, &params.Category)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category: %w", err).Error())
	}

	// ------------- Optional query parameter "stock" -------------

	err = runtime.BindQueryParameter("form", true, false, "stock", query, &params.Stock)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter stock: %w", err).Error())
	}

	// ------------- Optional query parameter "promo" -------------

	err = runtime.BindQueryParameter("form", true, false, "promo", query, &params.Promo)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter promo: %w", err).Error())
	}

	// ------------- Optional query parameter "expiry" -------------

	err = runtime.BindQueryParameter("form", true, false, "expiry", query, &params.Expiry)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter expiry: %w", err).Error())
	}

	// ------------- Optional query parameter "role" -------------

	err = runtime.BindQueryParameter("form", true, false, "role", query, &params.Role)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter role: %w", err).Error())
	}

	return siw.Handler.GetProducts(c, params)
}

// GetProductsAutoDiscounts operation middleware
func (siw *ServerInterfaceWrapper) GetProductsAutoDiscounts(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetProductsAutoDiscounts(c)
}

// GetProductsExpiryAlerts operation middleware
func (siw *ServerInterfaceWrapper) GetProductsExpiryAlerts(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetProductsExpiryAlerts(c)
}

// PatchProductsId operation middleware
func (siw *ServerInterfaceWrapper) PatchProductsId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PatchProductsId(c, id)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/admin/approvals", wrapper.GetAdminApprovals)

	router.Post(options.BaseURL+"/admin/approvals/:id/approve", wrapper.PostAdminApprovalsIdApprove)

	router.Post(options.BaseURL+"/admin/approvals/:id/reject", wrapper.PostAdminApprovalsIdReject)

	router.Get(options.BaseURL+"/admin/complaints", wrapper.GetAdminComplaints)

	router.Get(options.BaseURL+"/admin/complaints/:id/investigation", wrapper.GetAdminComplaintsIdInvestigation)

	router.Post(options.BaseURL+"/admin/complaints/:id/resolve", wrapper.PostAdminComplaintsIdResolve)

	router.Get(options.BaseURL+"/admin/onboarding-leads", wrapper.GetAdminOnboardingLeads)

	router.Post(options.BaseURL+"/admin/onboarding-leads/:id/notify", wrapper.PostAdminOnboardingLeadsIdNotify)

	router.Get(options.BaseURL+"/admin/partners", wrapper.GetAdminPartners)

	router.Post(options.BaseURL+"/admin/partners/:id/suspend", wrapper.PostAdminPartnersIdSuspend)

	router.Get(options.BaseURL+"/admin/reports/kpis", wrapper.GetAdminReportsKpis)

	router.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)

	router.Get(options.BaseURL+"/auth/me", wrapper.GetAuthMe)

	router.Patch(options.BaseURL+"/auth/profile", wrapper.PatchAuthProfile)

	router.Post(options.BaseURL+"/auth/send-otp", wrapper.PostAuthSendOtp)

	router.Post(options.BaseURL+"/auth/signup", wrapper.PostAuthSignup)

	router.Post(options.BaseURL+"/auth/verify-otp", wrapper.PostAuthVerifyOtp)

	router.Get(options.BaseURL+"/delivery/active-task", wrapper.GetDeliveryActiveTask)

	router.Get(options.BaseURL+"/delivery/earnings-insights", wrapper.GetDeliveryEarningsInsights)

	router.Get(options.BaseURL+"/delivery/earnings/weekly", wrapper.GetDeliveryEarningsWeekly)

	router.Get(options.BaseURL+"/delivery/kpis", wrapper.GetDeliveryKpis)

	router.Post(options.BaseURL+"/delivery/onboarding", wrapper.PostDeliveryOnboarding)

	router.Get(options.BaseURL+"/delivery/profile", wrapper.GetDeliveryProfile)

	router.Get(options.BaseURL+"/delivery/recommendations", wrapper.GetDeliveryRecommendations)

	router.Post(options.BaseURL+"/delivery/recommendations/ack", wrapper.PostDeliveryRecommendationsAck)

	router.Get(options.BaseURL+"/delivery/shifts", wrapper.GetDeliveryShifts)

	router.Get(options.BaseURL+"/delivery/sla-kpis", wrapper.GetDeliverySlaKpis)

	router.Get(options.BaseURL+"/delivery/trace/:orderId", wrapper.GetDeliveryTraceOrderId)

	router.Get(options.BaseURL+"/grocery/expiry-alerts", wrapper.GetGroceryExpiryAlerts)

	router.Get(options.BaseURL+"/grocery/kpis", wrapper.GetGroceryKpis)

	router.Post(options.BaseURL+"/grocery/onboarding", wrapper.PostGroceryOnboarding)

	router.Get(options.BaseURL+"/grocery/payout-summary", wrapper.GetGroceryPayoutSummary)

	router.Get(options.BaseURL+"/grocery/profile", wrapper.GetGroceryProfile)

	router.Get(options.BaseURL+"/grocery/stock-alerts", wrapper.GetGroceryStockAlerts)

	router.Get(options.BaseURL+"/orders", wrapper.GetOrders)

	router.Post(options.BaseURL+"/orders/:order_id/assign-delivery", wrapper.PostOrdersOrderIdAssignDelivery)

	router.Patch(options.BaseURL+"/orders/:order_id/status", wrapper.PatchOrdersOrderIdStatus)

	router.Get(options.BaseURL+"/products", wrapper.GetProducts)

	router.Get(options.BaseURL+"/products/auto-discounts", wrapper.GetProductsAutoDiscounts)

	router.Get(options.BaseURL+"/products/expiry-alerts", wrapper.GetProductsExpiryAlerts)

	router.Patch(options.BaseURL+"/products/:id", wrapper.PatchProductsId)

}
